version: '3'
services:
  db:
    image: postgres:13-alpine
    container_name: 'aiohttp-db-posgtres'
    volumes:
      - aiohttp-postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=aiohhtpdb
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
      
volumes:
  aiohttp-postgres_data:
